// Generated by CoffeeScript 1.6.3
'use strict';
describe('angularjsGruntExampleApp app', function() {
  beforeEach(function() {
    return browser().navigateTo('/');
  });
  return describe('Homepage', function() {
    return it('should display the correct route', function() {
      return expect(browser().location().path()).toBe('/');
    });
  });
});
