// Generated by CoffeeScript 1.6.3
'use strict';
angular.module('courtSearchApp').controller('PlaceListCtrl', function($scope, $http) {
  return $http.get('data/places.json').success(function(data) {
    return $scope.places = data;
  });
  /*
  $scope.places = [
    'HTML5 Boilerplate',
    'AngularJS',
    'Karma'
  ]
  */

});
